<a href="https://colab.research.google.com/github/sujin-create/finedu/blob/main/%EA%B8%88%EC%9C%B5%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D/(%EB%A7%9E%EC%B6%A4%ED%98%95_%EB%8F%99%EC%A0%84%EC%A3%BC%EB%A5%BC_%ED%99%9C%EC%9A%A9%ED%95%9C_%ED%88%AC%EB%A6%B0%EC%9D%B4_%EC%8B%A4%EC%A0%84%ED%88%AC%EC%9E%90_%EB%8F%84%EC%9A%B0%EB%AF%B8_%EC%84%9C%EB%B9%84%EC%8A%A4)_%EC%8B%A4%EC%A0%84%ED%88%AC%EC%9E%90_%08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **동전주 카테고리 분류**
- 1000원 미만의 동전주를 naver 금융차트를 **크롤링**을 활용해서 가져온다.

In [9]:
!wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1nIUZxASrbIa0Z2xzGVgX1dqjtnFCoKNT' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1nIUZxASrbIa0Z2xzGVgX1dqjtnFCoKNT" -O dart.csv && rm -rf /tmp/cookies.txt

--2022-07-29 10:57:06--  https://docs.google.com/uc?export=download&confirm=t&id=1nIUZxASrbIa0Z2xzGVgX1dqjtnFCoKNT
Resolving docs.google.com (docs.google.com)... 142.250.148.102, 142.250.148.138, 142.250.148.101, ...
Connecting to docs.google.com (docs.google.com)|142.250.148.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-04-7k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/u73sovodb12re8ns39mbrirqmo871fhv/1659092175000/17609157229046208934/*/1nIUZxASrbIa0Z2xzGVgX1dqjtnFCoKNT?e=download&uuid=34f19967-a0d5-4bb9-9e37-9609463e54be [following]
Warning: wildcards not supported in HTTP.
--2022-07-29 10:57:06--  https://doc-04-7k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/u73sovodb12re8ns39mbrirqmo871fhv/1659092175000/17609157229046208934/*/1nIUZxASrbIa0Z2xzGVgX1dqjtnFCoKNT?e=download&uuid=34f19967-a0d5-4bb9-9e37-9609463e54be
Resolving doc-04-7k-docs.googleusercontent.com (doc-04-7k-docs.googleusercontent.com)... 142.250.136.132, 2607:f8b0:4001:c34::84
Connecting to doc-04-7k-docs.googleusercontent.com (doc-04-7k-docs.googleusercontent.com)|142.250.136.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 125061598 (119M) [text/csv]
Saving to: ‘dart.csv’

dart.csv            100%[===================>] 119.27M   229MB/s    in 0.5s

2022-07-29 10:57:07 (229 MB/s) - ‘dart.csv’ saved [125061598/125061598]

In [10]:
import pandas as pd
from datetime import datetime
from matplotlib import dates as mdates
import matplotlib.pyplot as plt

In [11]:
df_all = pd.read_csv('/content/dart.csv',  sep=',')

In [12]:
df_all

,code,market,name,business
0,000020,KOSPI,동화약품,II. 사업의 내용\n1. 사업의 개요\n가. 일반적인 사항\n기업회계기준서 제11...
1,000040,KOSPI,KR모터스,II. 사업의 내용\n1. 사업의 개요\n가. 업계의 현황\n수출주력시장인 유럽 불...
2,000050,KOSPI,경방,II. 사업의 내용\n1. 사업의 개요\n(1) 산업의 특성\n[섬유사업부문]\n면...
3,000060,KOSPI,메리츠화재,"II. 사업의 내용\n1. 사업의 개요\n가. 산업의 특성, 성장성, 경기변동의 특..."
4,000070,KOSPI,삼양홀딩스,"II. 사업의 내용\n1. 사업의 개요\n가. 업계의 현황\n지주회사(持株會社, H..."
...,...,...,...,...
2584,950160,KOSDAQ,코오롱티슈진,II. 사업의 내용\n당사는 1999년 6월 9일 세포 유전자 기술 Platform...
2585,950170,KOSDAQ,JTC,II. 사업의 내용\n1. 사업의 개요\n가. 업계의 현황\n(1) 산업의 특성\n...
2586,950180,KOSDAQ,SNK,"II. 사업의 내용\n1. 사업의 개요\n당사는 연결실체 기준으로 모바일, 콘솔, ..."
2587,950190,KOSDAQ,미투젠,NaN
2588,950200,KOSDAQ,소마젠(Reg.S),NaN

In [13]:
import requests

In [14]:
!pip install beautifulSoup4

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: beautifulSoup4 in /usr/local/lib/python3.7/dist-packages (4.6.3)

In [15]:
# bs4라는 패키지로부터 BeautifulSoup라는 모듈을 임포트
from bs4 import BeautifulSoup as bs

In [16]:
# 102280 종목 "쌍방울"에 대한 카테고리
url = 'https://finance.naver.com/item/main.naver?code=102280'
headers = {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}
#크롤링 하는 것을 막는 웹사이트를 크롤링하기 위해서는 headers에 user-agent를 넣어서 가져올 수 있음
response = requests.get(url, headers=headers)
soup = bs(response.text, 'html.parser')
result = soup.select("h4 > em > a")[0].text
print(result)

섬유,의류,신발,호화품

In [17]:
df = pd.DataFrame()
site_url = 'https://finance.naver.com/sise/sise_market_sum.naver?'
for page in range(1, 38):
    page_url = '{}&page={}'.format(site_url, page)
    print(page_url)

    # 위에서 했던 일련의 과정들을 각 url에 대해서 (37(전체페이지)페이지에 대해서 반복)
    temp = pd.read_html(page_url,encoding='euc-kr')[1]
    # temp = temp[['종목명','현재가']]
    temp.dropna()
    temp = temp[temp['현재가']<1000] #1000원조건 
    # print(temp)
    # 현재 얻은 데이터프레임을 기존 데이터프레임에 누적.
    df = df.append(temp)

df=df.reset_index(drop=True)

https://finance.naver.com/sise/sise_market_sum.naver?&page=1
https://finance.naver.com/sise/sise_market_sum.naver?&page=2
https://finance.naver.com/sise/sise_market_sum.naver?&page=3
https://finance.naver.com/sise/sise_market_sum.naver?&page=4
https://finance.naver.com/sise/sise_market_sum.naver?&page=5
https://finance.naver.com/sise/sise_market_sum.naver?&page=6
https://finance.naver.com/sise/sise_market_sum.naver?&page=7
https://finance.naver.com/sise/sise_market_sum.naver?&page=8
https://finance.naver.com/sise/sise_market_sum.naver?&page=9
https://finance.naver.com/sise/sise_market_sum.naver?&page=10
https://finance.naver.com/sise/sise_market_sum.naver?&page=11
https://finance.naver.com/sise/sise_market_sum.naver?&page=12
https://finance.naver.com/sise/sise_market_sum.naver?&page=13
https://finance.naver.com/sise/sise_market_sum.naver?&page=14
https://finance.naver.com/sise/sise_market_sum.naver?&page=15
https://finance.naver.com/sise/sise_market_sum.naver?&page=16
https://finance.naver.com/sise/sise_market_sum.naver?&page=17
https://finance.naver.com/sise/sise_market_sum.naver?&page=18
https://finance.naver.com/sise/sise_market_sum.naver?&page=19
https://finance.naver.com/sise/sise_market_sum.naver?&page=20
https://finance.naver.com/sise/sise_market_sum.naver?&page=21
https://finance.naver.com/sise/sise_market_sum.naver?&page=22
https://finance.naver.com/sise/sise_market_sum.naver?&page=23
https://finance.naver.com/sise/sise_market_sum.naver?&page=24
https://finance.naver.com/sise/sise_market_sum.naver?&page=25
https://finance.naver.com/sise/sise_market_sum.naver?&page=26
https://finance.naver.com/sise/sise_market_sum.naver?&page=27
https://finance.naver.com/sise/sise_market_sum.naver?&page=28
https://finance.naver.com/sise/sise_market_sum.naver?&page=29
https://finance.naver.com/sise/sise_market_sum.naver?&page=30
https://finance.naver.com/sise/sise_market_sum.naver?&page=31
https://finance.naver.com/sise/sise_market_sum.naver?&page=32
https://finance.naver.com/sise/sise_market_sum.naver?&page=33
https://finance.naver.com/sise/sise_market_sum.naver?&page=34
https://finance.naver.com/sise/sise_market_sum.naver?&page=35
https://finance.naver.com/sise/sise_market_sum.naver?&page=36
https://finance.naver.com/sise/sise_market_sum.naver?&page=37

In [18]:
df.to_csv('coinstock.csv',index=False)

In [70]:
df = pd.read_csv('coinstock.csv')

In [104]:
df = df[['종목명','현재가','등락률','액면가','시가총액','상장주식수','거래량','PER','ROE']]

In [105]:
df.dropna()

,종목명,현재가,등락률,액면가,시가총액,상장주식수,거래량,PER,ROE
0,우리종금,914.0,0.00%,500.0,7990.0,874203.0,1527786.0,9.62,14.16
1,SK증권,761.0,+1.06%,500.0,3596.0,472590.0,2091324.0,14.92,6.77
2,에이프로젠제약,672.0,+3.54%,500.0,2678.0,398576.0,1402199.0,29.22,1.60
3,DB,830.0,+2.22%,500.0,1670.0,201174.0,276426.0,7.76,5.78
4,쌍방울,557.0,+0.54%,500.0,1463.0,262592.0,2483715.0,-4.32,-8.37
5,IHQ,753.0,+0.27%,500.0,1244.0,165140.0,257641.0,-18.37,-8.70
6,SG세계물산,589.0,+0.68%,500.0,1192.0,202425.0,497338.0,2.33,21.32
7,대유플러스,947.0,+0.42%,500.0,1146.0,120999.0,238297.0,-55.71,-2.17
8,보해양조,764.0,+1.06%,500.0,1063.0,139120.0,248109.0,-44.94,-1.12
9,대유에이텍,859.0,+0.47%,500.0,989.0,115095.0,167046.0,-3.83,-14.41
11,오리엔트바이오,815.0,+2.77%,500.0,966.0,118583.0,328199.0,2.83,51.92
12,서울식품,253.0,0.00%,100.0,948.0,374756.0,1471997.0,-25.30,-21.25
13,큐로,405.0,+0.50%,500.0,936.0,231212.0,166117.0,-7.79,-12.68
14,메타랩스,745.0,+0.27%,500.0,928.0,124523.0,168109.0,-3.43,-27.64
15,영흥,828.0,+0.61%,500.0,839.0,101310.0,118207.0,10.35,3.58
16,엔케이,965.0,+4.78%,500.0,772.0,79983.0,146517.0,7.37,11.62
17,제이준코스메틱,962.0,+1.05%,500.0,741.0,76983.0,210022.0,-1.60,-63.88
18,KR모터스,728.0,+1.39%,500.0,700.0,96138.0,563489.0,-6.80,-25.82
19,윌비스,984.0,-0.91%,1000.0,662.0,67236.0,280615.0,-8.95,-8.01
20,티웨이홀딩스,543.0,+1.31%,500.0,594.0,109472.0,185715.0,-0.86,-118.36
21,케이비아이동국실업,678.0,-0.73%,500.0,592.0,87286.0,117512.0,-1.89,-13.24
22,부산주공,838.0,+6.48%,500.0,553.0,65974.0,21599517.0,-4.73,-47.16
23,인디에프,780.0,+0.52%,500.0,552.0,70713.0,11778.0,-2.47,-50.83
24,주연테크,893.0,-1.33%,200.0,529.0,59199.0,127885.0,-28.81,8.09
25,참엔지니어링,836.0,+0.36%,500.0,492.0,58867.0,116685.0,-6.48,-2.55
26,미래아이앤지,335.0,0.00%,100.0,434.0,129484.0,280729.0,-2.13,-22.53
27,동원금속,906.0,+1.34%,500.0,424.0,46755.0,83830.0,1.87,48.51
28,성안,728.0,+0.55%,500.0,414.0,56858.0,1458275.0,1.70,87.37
29,코아스,971.0,+0.52%,500.0,300.0,30907.0,45506.0,-5.28,-25.16
31,비케이탑스,904.0,0.00%,500.0,192.0,21248.0,0.0,-0.35,-243.33

In [106]:
codes=[0]*len(df)
count=0
for i in df['종목명'].values:
  code = df_all[df_all['name']==i].code.values
  if len(code):
    codes[count] = code[0]
  else:
    codes[count]='nan'
  count = count+1
codes

['010050',
 '001510',
 '003060',
 '012030',
 '102280',
 '003560',
 '004060',
 '000300',
 '000890',
 '002880',
 '031820',
 '002630',
 '004410',
 '015590',
 '090370',
 '012160',
 '085310',
 '025620',
 '000040',
 '008600',
 '004870',
 '001620',
 '005030',
 '014990',
 '044380',
 '009310',
 '007120',
 '018500',
 '011300',
 '071950',
 '096300',
 '030790']

In [107]:
df['code'] = codes

In [108]:
df

,종목명,현재가,등락률,액면가,시가총액,상장주식수,거래량,PER,ROE,code
0,우리종금,914.0,0.00%,500.0,7990.0,874203.0,1527786.0,9.62,14.16,010050
1,SK증권,761.0,+1.06%,500.0,3596.0,472590.0,2091324.0,14.92,6.77,001510
2,에이프로젠제약,672.0,+3.54%,500.0,2678.0,398576.0,1402199.0,29.22,1.60,003060
3,DB,830.0,+2.22%,500.0,1670.0,201174.0,276426.0,7.76,5.78,012030
4,쌍방울,557.0,+0.54%,500.0,1463.0,262592.0,2483715.0,-4.32,-8.37,102280
5,IHQ,753.0,+0.27%,500.0,1244.0,165140.0,257641.0,-18.37,-8.70,003560
6,SG세계물산,589.0,+0.68%,500.0,1192.0,202425.0,497338.0,2.33,21.32,004060
7,대유플러스,947.0,+0.42%,500.0,1146.0,120999.0,238297.0,-55.71,-2.17,000300
8,보해양조,764.0,+1.06%,500.0,1063.0,139120.0,248109.0,-44.94,-1.12,000890
9,대유에이텍,859.0,+0.47%,500.0,989.0,115095.0,167046.0,-3.83,-14.41,002880
10,콤텍시스템,810.0,+1.12%,500.0,981.0,121051.0,287094.0,NaN,2.03,031820
11,오리엔트바이오,815.0,+2.77%,500.0,966.0,118583.0,328199.0,2.83,51.92,002630
12,서울식품,253.0,0.00%,100.0,948.0,374756.0,1471997.0,-25.30,-21.25,004410
13,큐로,405.0,+0.50%,500.0,936.0,231212.0,166117.0,-7.79,-12.68,015590
14,메타랩스,745.0,+0.27%,500.0,928.0,124523.0,168109.0,-3.43,-27.64,090370
15,영흥,828.0,+0.61%,500.0,839.0,101310.0,118207.0,10.35,3.58,012160
16,엔케이,965.0,+4.78%,500.0,772.0,79983.0,146517.0,7.37,11.62,085310
17,제이준코스메틱,962.0,+1.05%,500.0,741.0,76983.0,210022.0,-1.60,-63.88,025620
18,KR모터스,728.0,+1.39%,500.0,700.0,96138.0,563489.0,-6.80,-25.82,000040
19,윌비스,984.0,-0.91%,1000.0,662.0,67236.0,280615.0,-8.95,-8.01,008600
20,티웨이홀딩스,543.0,+1.31%,500.0,594.0,109472.0,185715.0,-0.86,-118.36,004870
21,케이비아이동국실업,678.0,-0.73%,500.0,592.0,87286.0,117512.0,-1.89,-13.24,001620
22,부산주공,838.0,+6.48%,500.0,553.0,65974.0,21599517.0,-4.73,-47.16,005030
23,인디에프,780.0,+0.52%,500.0,552.0,70713.0,11778.0,-2.47,-50.83,014990
24,주연테크,893.0,-1.33%,200.0,529.0,59199.0,127885.0,-28.81,8.09,044380
25,참엔지니어링,836.0,+0.36%,500.0,492.0,58867.0,116685.0,-6.48,-2.55,009310
26,미래아이앤지,335.0,0.00%,100.0,434.0,129484.0,280729.0,-2.13,-22.53,007120
27,동원금속,906.0,+1.34%,500.0,424.0,46755.0,83830.0,1.87,48.51,018500
28,성안,728.0,+0.55%,500.0,414.0,56858.0,1458275.0,1.70,87.37,011300
29,코아스,971.0,+0.52%,500.0,300.0,30907.0,45506.0,-5.28,-25.16,071950
30,베트남개발1,207.0,0.00%,0.0,285.0,137680.0,24118.0,NaN,NaN,096300
31,비케이탑스,904.0,0.00%,500.0,192.0,21248.0,0.0,-0.35,-243.33,030790

In [112]:
df = df[df['code']!='nan'] #선물은 주식투자 일반 주식투자 교육을 하는데 부적합하기에 제외

In [113]:
df = df.reset_index(drop=True)

In [114]:
df

,종목명,현재가,등락률,액면가,시가총액,상장주식수,거래량,PER,ROE,code
0,우리종금,914.0,0.00%,500.0,7990.0,874203.0,1527786.0,9.62,14.16,010050
1,SK증권,761.0,+1.06%,500.0,3596.0,472590.0,2091324.0,14.92,6.77,001510
2,에이프로젠제약,672.0,+3.54%,500.0,2678.0,398576.0,1402199.0,29.22,1.60,003060
3,DB,830.0,+2.22%,500.0,1670.0,201174.0,276426.0,7.76,5.78,012030
4,쌍방울,557.0,+0.54%,500.0,1463.0,262592.0,2483715.0,-4.32,-8.37,102280
5,IHQ,753.0,+0.27%,500.0,1244.0,165140.0,257641.0,-18.37,-8.70,003560
6,SG세계물산,589.0,+0.68%,500.0,1192.0,202425.0,497338.0,2.33,21.32,004060
7,대유플러스,947.0,+0.42%,500.0,1146.0,120999.0,238297.0,-55.71,-2.17,000300
8,보해양조,764.0,+1.06%,500.0,1063.0,139120.0,248109.0,-44.94,-1.12,000890
9,대유에이텍,859.0,+0.47%,500.0,989.0,115095.0,167046.0,-3.83,-14.41,002880
10,콤텍시스템,810.0,+1.12%,500.0,981.0,121051.0,287094.0,NaN,2.03,031820
11,오리엔트바이오,815.0,+2.77%,500.0,966.0,118583.0,328199.0,2.83,51.92,002630
12,서울식품,253.0,0.00%,100.0,948.0,374756.0,1471997.0,-25.30,-21.25,004410
13,큐로,405.0,+0.50%,500.0,936.0,231212.0,166117.0,-7.79,-12.68,015590
14,메타랩스,745.0,+0.27%,500.0,928.0,124523.0,168109.0,-3.43,-27.64,090370
15,영흥,828.0,+0.61%,500.0,839.0,101310.0,118207.0,10.35,3.58,012160
16,엔케이,965.0,+4.78%,500.0,772.0,79983.0,146517.0,7.37,11.62,085310
17,제이준코스메틱,962.0,+1.05%,500.0,741.0,76983.0,210022.0,-1.60,-63.88,025620
18,KR모터스,728.0,+1.39%,500.0,700.0,96138.0,563489.0,-6.80,-25.82,000040
19,윌비스,984.0,-0.91%,1000.0,662.0,67236.0,280615.0,-8.95,-8.01,008600
20,티웨이홀딩스,543.0,+1.31%,500.0,594.0,109472.0,185715.0,-0.86,-118.36,004870
21,케이비아이동국실업,678.0,-0.73%,500.0,592.0,87286.0,117512.0,-1.89,-13.24,001620
22,부산주공,838.0,+6.48%,500.0,553.0,65974.0,21599517.0,-4.73,-47.16,005030
23,인디에프,780.0,+0.52%,500.0,552.0,70713.0,11778.0,-2.47,-50.83,014990
24,주연테크,893.0,-1.33%,200.0,529.0,59199.0,127885.0,-28.81,8.09,044380
25,참엔지니어링,836.0,+0.36%,500.0,492.0,58867.0,116685.0,-6.48,-2.55,009310
26,미래아이앤지,335.0,0.00%,100.0,434.0,129484.0,280729.0,-2.13,-22.53,007120
27,동원금속,906.0,+1.34%,500.0,424.0,46755.0,83830.0,1.87,48.51,018500
28,성안,728.0,+0.55%,500.0,414.0,56858.0,1458275.0,1.70,87.37,011300
29,코아스,971.0,+0.52%,500.0,300.0,30907.0,45506.0,-5.28,-25.16,071950
30,베트남개발1,207.0,0.00%,0.0,285.0,137680.0,24118.0,NaN,NaN,096300
31,비케이탑스,904.0,0.00%,500.0,192.0,21248.0,0.0,-0.35,-243.33,030790

동전주의 카테고리 분류를 위한 크롤링을 진행

In [115]:
results=[]
for i in df['code'].values:
  url = 'https://finance.naver.com/item/main.naver?code={0}'.format(i)
  headers = {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}
  #크롤링 하는 것을 막는 웹사이트를 크롤링하기 위해서는 headers에 user-agent를 넣어서 가져올 수 있음
  response = requests.get(url, headers=headers)
  soup = bs(response.text, 'html.parser')
  print(url)
  try: 
    result = soup.select("h4 > em > a")[0].text
    results.append(result)
  except: 
    print('error')
    results.append('해당사항없음')

https://finance.naver.com/item/main.naver?code=010050
https://finance.naver.com/item/main.naver?code=001510
https://finance.naver.com/item/main.naver?code=003060
https://finance.naver.com/item/main.naver?code=012030
https://finance.naver.com/item/main.naver?code=102280
https://finance.naver.com/item/main.naver?code=003560
https://finance.naver.com/item/main.naver?code=004060
https://finance.naver.com/item/main.naver?code=000300
https://finance.naver.com/item/main.naver?code=000890
https://finance.naver.com/item/main.naver?code=002880
https://finance.naver.com/item/main.naver?code=031820
https://finance.naver.com/item/main.naver?code=002630
https://finance.naver.com/item/main.naver?code=004410
https://finance.naver.com/item/main.naver?code=015590
https://finance.naver.com/item/main.naver?code=090370
https://finance.naver.com/item/main.naver?code=012160
https://finance.naver.com/item/main.naver?code=085310
https://finance.naver.com/item/main.naver?code=025620
https://finance.naver.com/item/main.naver?code=000040
https://finance.naver.com/item/main.naver?code=008600
https://finance.naver.com/item/main.naver?code=004870
https://finance.naver.com/item/main.naver?code=001620
https://finance.naver.com/item/main.naver?code=005030
https://finance.naver.com/item/main.naver?code=014990
https://finance.naver.com/item/main.naver?code=044380
https://finance.naver.com/item/main.naver?code=009310
https://finance.naver.com/item/main.naver?code=007120
https://finance.naver.com/item/main.naver?code=018500
https://finance.naver.com/item/main.naver?code=011300
https://finance.naver.com/item/main.naver?code=071950
https://finance.naver.com/item/main.naver?code=096300
error
https://finance.naver.com/item/main.naver?code=030790

In [116]:
print(results)
df['category'] = results

['기타금융', '증권', '제약', 'IT서비스', '섬유,의류,신발,호화품', '방송과엔터테인먼트', '섬유,의류,신발,호화품', '자동차부품', '음료', '자동차부품', 'IT서비스', '생물공학', '식품', '기계', '섬유,의류,신발,호화품', '철강', '기계', '화장품', '자동차', '섬유,의류,신발,호화품', '항공사', '자동차부품', '자동차부품', '섬유,의류,신발,호화품', '컴퓨터와주변기기', '디스플레이장비및부품', 'IT서비스', '자동차부품', '섬유,의류,신발,호화품', '가구', '해당사항없음', '섬유,의류,신발,호화품']

In [117]:
df

,종목명,현재가,등락률,액면가,시가총액,상장주식수,거래량,PER,ROE,code,category
0,우리종금,914.0,0.00%,500.0,7990.0,874203.0,1527786.0,9.62,14.16,010050,기타금융
1,SK증권,761.0,+1.06%,500.0,3596.0,472590.0,2091324.0,14.92,6.77,001510,증권
2,에이프로젠제약,672.0,+3.54%,500.0,2678.0,398576.0,1402199.0,29.22,1.60,003060,제약
3,DB,830.0,+2.22%,500.0,1670.0,201174.0,276426.0,7.76,5.78,012030,IT서비스
4,쌍방울,557.0,+0.54%,500.0,1463.0,262592.0,2483715.0,-4.32,-8.37,102280,"섬유,의류,신발,호화품"
5,IHQ,753.0,+0.27%,500.0,1244.0,165140.0,257641.0,-18.37,-8.70,003560,방송과엔터테인먼트
6,SG세계물산,589.0,+0.68%,500.0,1192.0,202425.0,497338.0,2.33,21.32,004060,"섬유,의류,신발,호화품"
7,대유플러스,947.0,+0.42%,500.0,1146.0,120999.0,238297.0,-55.71,-2.17,000300,자동차부품
8,보해양조,764.0,+1.06%,500.0,1063.0,139120.0,248109.0,-44.94,-1.12,000890,음료
9,대유에이텍,859.0,+0.47%,500.0,989.0,115095.0,167046.0,-3.83,-14.41,002880,자동차부품
10,콤텍시스템,810.0,+1.12%,500.0,981.0,121051.0,287094.0,NaN,2.03,031820,IT서비스
11,오리엔트바이오,815.0,+2.77%,500.0,966.0,118583.0,328199.0,2.83,51.92,002630,생물공학
12,서울식품,253.0,0.00%,100.0,948.0,374756.0,1471997.0,-25.30,-21.25,004410,식품
13,큐로,405.0,+0.50%,500.0,936.0,231212.0,166117.0,-7.79,-12.68,015590,기계
14,메타랩스,745.0,+0.27%,500.0,928.0,124523.0,168109.0,-3.43,-27.64,090370,"섬유,의류,신발,호화품"
15,영흥,828.0,+0.61%,500.0,839.0,101310.0,118207.0,10.35,3.58,012160,철강
16,엔케이,965.0,+4.78%,500.0,772.0,79983.0,146517.0,7.37,11.62,085310,기계
17,제이준코스메틱,962.0,+1.05%,500.0,741.0,76983.0,210022.0,-1.60,-63.88,025620,화장품
18,KR모터스,728.0,+1.39%,500.0,700.0,96138.0,563489.0,-6.80,-25.82,000040,자동차
19,윌비스,984.0,-0.91%,1000.0,662.0,67236.0,280615.0,-8.95,-8.01,008600,"섬유,의류,신발,호화품"
20,티웨이홀딩스,543.0,+1.31%,500.0,594.0,109472.0,185715.0,-0.86,-118.36,004870,항공사
21,케이비아이동국실업,678.0,-0.73%,500.0,592.0,87286.0,117512.0,-1.89,-13.24,001620,자동차부품
22,부산주공,838.0,+6.48%,500.0,553.0,65974.0,21599517.0,-4.73,-47.16,005030,자동차부품
23,인디에프,780.0,+0.52%,500.0,552.0,70713.0,11778.0,-2.47,-50.83,014990,"섬유,의류,신발,호화품"
24,주연테크,893.0,-1.33%,200.0,529.0,59199.0,127885.0,-28.81,8.09,044380,컴퓨터와주변기기
25,참엔지니어링,836.0,+0.36%,500.0,492.0,58867.0,116685.0,-6.48,-2.55,009310,디스플레이장비및부품
26,미래아이앤지,335.0,0.00%,100.0,434.0,129484.0,280729.0,-2.13,-22.53,007120,IT서비스
27,동원금속,906.0,+1.34%,500.0,424.0,46755.0,83830.0,1.87,48.51,018500,자동차부품
28,성안,728.0,+0.55%,500.0,414.0,56858.0,1458275.0,1.70,87.37,011300,"섬유,의류,신발,호화품"
29,코아스,971.0,+0.52%,500.0,300.0,30907.0,45506.0,-5.28,-25.16,071950,가구
30,베트남개발1,207.0,0.00%,0.0,285.0,137680.0,24118.0,NaN,NaN,096300,해당사항없음
31,비케이탑스,904.0,0.00%,500.0,192.0,21248.0,0.0,-0.35,-243.33,030790,"섬유,의류,신발,호화품"

In [118]:
df.to_csv('coin_stock.csv',index=False)

In [119]:
df= pd.read_csv('coin_stock.csv')

In [120]:
df

,종목명,현재가,등락률,액면가,시가총액,상장주식수,거래량,PER,ROE,code,category
0,우리종금,914.0,0.00%,500.0,7990.0,874203.0,1527786.0,9.62,14.16,10050,기타금융
1,SK증권,761.0,+1.06%,500.0,3596.0,472590.0,2091324.0,14.92,6.77,1510,증권
2,에이프로젠제약,672.0,+3.54%,500.0,2678.0,398576.0,1402199.0,29.22,1.60,3060,제약
3,DB,830.0,+2.22%,500.0,1670.0,201174.0,276426.0,7.76,5.78,12030,IT서비스
4,쌍방울,557.0,+0.54%,500.0,1463.0,262592.0,2483715.0,-4.32,-8.37,102280,"섬유,의류,신발,호화품"
5,IHQ,753.0,+0.27%,500.0,1244.0,165140.0,257641.0,-18.37,-8.70,3560,방송과엔터테인먼트
6,SG세계물산,589.0,+0.68%,500.0,1192.0,202425.0,497338.0,2.33,21.32,4060,"섬유,의류,신발,호화품"
7,대유플러스,947.0,+0.42%,500.0,1146.0,120999.0,238297.0,-55.71,-2.17,300,자동차부품
8,보해양조,764.0,+1.06%,500.0,1063.0,139120.0,248109.0,-44.94,-1.12,890,음료
9,대유에이텍,859.0,+0.47%,500.0,989.0,115095.0,167046.0,-3.83,-14.41,2880,자동차부품
10,콤텍시스템,810.0,+1.12%,500.0,981.0,121051.0,287094.0,NaN,2.03,31820,IT서비스
11,오리엔트바이오,815.0,+2.77%,500.0,966.0,118583.0,328199.0,2.83,51.92,2630,생물공학
12,서울식품,253.0,0.00%,100.0,948.0,374756.0,1471997.0,-25.30,-21.25,4410,식품
13,큐로,405.0,+0.50%,500.0,936.0,231212.0,166117.0,-7.79,-12.68,15590,기계
14,메타랩스,745.0,+0.27%,500.0,928.0,124523.0,168109.0,-3.43,-27.64,90370,"섬유,의류,신발,호화품"
15,영흥,828.0,+0.61%,500.0,839.0,101310.0,118207.0,10.35,3.58,12160,철강
16,엔케이,965.0,+4.78%,500.0,772.0,79983.0,146517.0,7.37,11.62,85310,기계
17,제이준코스메틱,962.0,+1.05%,500.0,741.0,76983.0,210022.0,-1.60,-63.88,25620,화장품
18,KR모터스,728.0,+1.39%,500.0,700.0,96138.0,563489.0,-6.80,-25.82,40,자동차
19,윌비스,984.0,-0.91%,1000.0,662.0,67236.0,280615.0,-8.95,-8.01,8600,"섬유,의류,신발,호화품"
20,티웨이홀딩스,543.0,+1.31%,500.0,594.0,109472.0,185715.0,-0.86,-118.36,4870,항공사
21,케이비아이동국실업,678.0,-0.73%,500.0,592.0,87286.0,117512.0,-1.89,-13.24,1620,자동차부품
22,부산주공,838.0,+6.48%,500.0,553.0,65974.0,21599517.0,-4.73,-47.16,5030,자동차부품
23,인디에프,780.0,+0.52%,500.0,552.0,70713.0,11778.0,-2.47,-50.83,14990,"섬유,의류,신발,호화품"
24,주연테크,893.0,-1.33%,200.0,529.0,59199.0,127885.0,-28.81,8.09,44380,컴퓨터와주변기기
25,참엔지니어링,836.0,+0.36%,500.0,492.0,58867.0,116685.0,-6.48,-2.55,9310,디스플레이장비및부품
26,미래아이앤지,335.0,0.00%,100.0,434.0,129484.0,280729.0,-2.13,-22.53,7120,IT서비스
27,동원금속,906.0,+1.34%,500.0,424.0,46755.0,83830.0,1.87,48.51,18500,자동차부품
28,성안,728.0,+0.55%,500.0,414.0,56858.0,1458275.0,1.70,87.37,11300,"섬유,의류,신발,호화품"
29,코아스,971.0,+0.52%,500.0,300.0,30907.0,45506.0,-5.28,-25.16,71950,가구
30,베트남개발1,207.0,0.00%,0.0,285.0,137680.0,24118.0,NaN,NaN,96300,해당사항없음
31,비케이탑스,904.0,0.00%,500.0,192.0,21248.0,0.0,-0.35,-243.33,30790,"섬유,의류,신발,호화품"

In [121]:
set(df['category'].values) # 총 20개의 카테고리로 분류됨

{'IT서비스',
 '가구',
 '기계',
 '기타금융',
 '디스플레이장비및부품',
 '방송과엔터테인먼트',
 '생물공학',
 '섬유,의류,신발,호화품',
 '식품',
 '음료',
 '자동차',
 '자동차부품',
 '제약',
 '증권',
 '철강',
 '컴퓨터와주변기기',
 '항공사',
 '해당사항없음',
 '화장품'}

# **사용자 맞춤형 카테고리로 분류된 coin주를 추천해 관심을 높인다.**

- 마이데이터를 활용하여 사용자의 관심있는 분야를 20개의 카테고리에서 결정
- 만약 사용자가 "섬유,의류,신발,호화품"에 관심이 있는 것으로 보인다면, "섬유,의류,신발,호화품"카테고리의 동전주로 투자하도록 유도
- 관심있는 카테고리의 동전주를 보여줌으로써, 참여도를 높임

In [ ]:
# 마이데이터를 활용한 카테고리 분류 코드 넣기

In [122]:
category = "섬유,의류,신발,호화품" # 사용자의 마이데이터를 확인

In [123]:
interests = df[df['category']==category]
interests = interests.reset_index(drop=True)
interests # 관심있는 coin stock이 총 7개가 나오는 것을 확인가능

,종목명,현재가,등락률,액면가,시가총액,상장주식수,거래량,PER,ROE,code,category
0,쌍방울,557.0,+0.54%,500.0,1463.0,262592.0,2483715.0,-4.32,-8.37,102280,"섬유,의류,신발,호화품"
1,SG세계물산,589.0,+0.68%,500.0,1192.0,202425.0,497338.0,2.33,21.32,4060,"섬유,의류,신발,호화품"
2,메타랩스,745.0,+0.27%,500.0,928.0,124523.0,168109.0,-3.43,-27.64,90370,"섬유,의류,신발,호화품"
3,윌비스,984.0,-0.91%,1000.0,662.0,67236.0,280615.0,-8.95,-8.01,8600,"섬유,의류,신발,호화품"
4,인디에프,780.0,+0.52%,500.0,552.0,70713.0,11778.0,-2.47,-50.83,14990,"섬유,의류,신발,호화품"
5,성안,728.0,+0.55%,500.0,414.0,56858.0,1458275.0,1.70,87.37,11300,"섬유,의류,신발,호화품"
6,비케이탑스,904.0,0.00%,500.0,192.0,21248.0,0.0,-0.35,-243.33,30790,"섬유,의류,신발,호화품"

# **맞춤형 카테고리에 해당하는 동전주의 관련 기사를 보여주고 종목을 고르도록 올바른 투자습관을 제공**

- naver 뉴스창를 활용해 추천 동전주들의 뉴스기사를 크롤링 해온다

In [124]:
from ast import keyword
import requests
from bs4 import BeautifulSoup

In [91]:
#pip install pyautogui

In [125]:
print("투자전 우리는 해당 주식이 오를것인가?를 고민해야합니다. 묻지마투자는 이제 그만하세요!!")

# 종목별로 관련 뉴스를 먼저 보여줌으로써, 묻지마 투자 습관을 버리고 공부후투자로 습관을 바로잡음
for interest in interests['종목명'].values:
  resp = requests.get(f"https://search.naver.com/search.naver?where=news&sm=tab_jum&query=동전주{interest}") # interest coin input으로 받음
  print('<<<{0}>>>뉴스를 읽고 투자를 결정하세요'.format(interest))
  html = resp.text
  soup = BeautifulSoup(html,"html.parser")
  links = soup.select('.news_tit')
  for link in links: #각 link는 <a>내용 </a> 의 html
      title = link.text # 태그 안에 텍스트요소 가져온다! -> 제목
      url = link.attrs['href'] # href=""의 속성값을 가져온다. -> 링크
      print(title, url) # 제목, 링크 크롤링 완료!
  print("\n")

투자전 우리는 해당 주식이 오를것인가?를 고민해야합니다. 묻지마투자는 이제 그만하세요!!
<<<쌍방울>>>뉴스를 읽고 투자를 결정하세요
쌍용차 품겠다는 쌍방울·이엔플러스, 작전주일까 구세주일까 http://www.newsway.co.kr/news/view?tp=1&ud=2022040517182001915
쌍용차 인수설에 주가 '널뛰기'…제2의 에디슨모터스 사태 오나 http://www.edaily.co.kr/news/newspath.asp?newsid=01108646632293496
[재무제표로 본 기업의 속살](19)인생역전이냐 꼬임이냐, 동전주의 ‘두 얼굴... http://weekly.khan.co.kr/khnm.html?mode=view&code=114&artid=202112171323301
남선알미우ㆍ쌍방울 수직 상승 http://www.pinpointnews.co.kr/news/articleView.html?idxno=106693
"이러다 개미들 다 털리겠네"…지루한 증시, 테마주만 활활 http://news.mk.co.kr/newsRead.php?no=353470&year=2022
[NW리포트]테마주에 멍드는 K-증시…시장 체질 개선·공시책임 강화 '급선무' http://www.newsway.co.kr/news/view?tp=1&ud=2022041916181812957
너도나도 테마주 올라타기…'혹시'는 없다 https://www.mk.co.kr/economy/view/2022/335664
중국업체과 손만 잡았다 하면 폭등 속출..거래소 모니터링中 http://news.mtn.co.kr/newscenter/news_viewer.mtn?gidx=2015092313112148962
1천원 미만 '동전주', 올 수익률 1위는… http://fn.segye.com/articles/article.asp?aid=20111225001620&cid=0503010000000
[특징주]쌍방울, 투자경고종목 지정에 ↓ http://www.etoday.co.kr/news/section/newsview.php?idxno=987506


<<<SG세계물산>>>뉴스를 읽고 투자를 결정하세요
[데이터 뉴스룸] 유통·무역業, 상반기에 주가 20% 넘게 뛴 4곳은?…CJ프레시... http://www.greened.kr/news/articleView.html?idxno=296355
증시 1년전보다 호황인데 동전株는 증가…수익률은 '쪽박' http://view.asiae.co.kr/news/view.htm?idxno=2018030210531666385
주식시장 ´큰손´개미들 줄었다…대량주문 감소 http://www.ebn.co.kr/news/n_view.html?id=582366
몇백원짜리 동전株의 반란 http://www.fnnews.com/view?ra=Sent0301m_01A&corp=fnnews&arcid=201202230100208970010759&cDateYear=2012&cDateMonth=02&cDateDay=23&
개인 투자자 주식 거래, 연초 대비 23% 감소 http://news.mk.co.kr/news_forward.php?domain=news&no=835450&year=2012
유니모씨앤씨, 올해 617%↑..상승률 챔피온 http://www.mt.co.kr/view/mtview.php?type=1&no=2012122809094959463&outlink=1


<<<메타랩스>>>뉴스를 읽고 투자를 결정하세요
[바이오 편승 후유증]우후죽순 진출…“녹록지 않네” http://www.edaily.co.kr/news/newspath.asp?newsid=01275926622716880


<<<윌비스>>>뉴스를 읽고 투자를 결정하세요
우량주보다 동전주? 저점 대비 수익률 무려 35% http://www.metroseoul.co.kr/article/20200423500371
[데이터 뉴스룸] 유통·무역業, 상반기에 주가 20% 넘게 뛴 4곳은?…CJ프레시... http://www.greened.kr/news/articleView.html?idxno=296355
[정치 테마주의 운명] 문재인 테마주, 2월 초부터 부각…정책주 ‘상승세’ http://magazine.hankyung.com/business/apps/news?popup=0&nid=01&c1=1001&nkey=2012101800881000051&mode=sub_view
21일 주식 시장 거래량 상위종목..1위 한진해운 http://www.breaknews.com/sub_read.html?uid=464079§ion=sc3
답답한 박근혜株…돈 되는 비트코인株 http://view.asiae.co.kr/news/view.htm?idxno=2013122609580233531
'朴근혜 vs 安철수' 테마주..증시 대권 지형은? http://www.newdaily.co.kr/news/article.html?no=116851


<<<인디에프>>>뉴스를 읽고 투자를 결정하세요
[여의도퍼트롤]종목도 싼 게 비지떡?…황제주 오를때 동전주 더 빠져 http://www.hankyung.com/news/app/newsview.php?aid=2013042394006
동전주 줄어든 대신 고가주 늘어 http://www.ajunews.com/kor/view.jsp?newsId=20130710000304
올해 코스닥 1천 원 이하 '동전주' 줄었다 http://news20.busan.com/controller/newsController.jsp?newsId=20130712000034
올해 들어 코스닥 동전주 14% 감소 https://n.news.naver.com/mnews/article/001/0006363495?sid=101
인디에프, 북한리스크에 16일만에 무너진 지폐주의 꿈 http://www.etoday.co.kr/news/section/newsview.php?idxno=715929
[베스트&워스트]코스피, 4년간 적자를 흑자로 공시한 ‘한신공영’ 33% 뚝 http://www.etoday.co.kr/news/section/newsview.php?idxno=981392
SK증권·일신바이오·대성창투, 더이상 동전株 아닙니다 http://www.hankyung.com/news/app/newsview.php?aid=2014080772941
고가주 ‘늘고’ 저가주 ‘줄고’ http://www.fnnews.com/view?ra=Sent0301m_01A&corp=fnnews&arcid=201307110334329683432968&cDateYear=2013&cDateMonth=07&cDateDay=11&
올들어 가장 많이 오른 종목은 230% 오른 바로… http://news.mk.co.kr/news_forward.php?domain=news&no=564902&year=2013
올해 고가주 비중 늘었다 http://www.dt.co.kr/contents.html?article_no=2013071002019957780003


<<<성안>>>뉴스를 읽고 투자를 결정하세요
'상폐위기' 성안, 반기보고서도 '의견거절'  http://www.sisaweek.com/news/articleView.html?idxno=146508
'성안' 주가 왜 상한가?…이유 물어보니 http://www.todaykorea.co.kr/news/articleView.html?idxno=282431
반년 만에 두배 넘게 오른 동전주… 10개 중 7개는 대선테마 https://biz.chosun.com/stock/analysis-prospect/2021/07/26/I7Y2Z7O7ZRGRBAT4Q5EE66VTHE/?utm_source=naver&utm_medium=original&utm_campaign=biz
'이재명 테마주'서 상폐 위기로… 위태로운 성안 http://www.sisaweek.com/news/articleView.html?idxno=143231
'이재명 테마주' 성안 향한 불편한 시선 http://www.sisaweek.com/news/articleView.html?idxno=142207
급등 ‘테마株’, 어떤 게 있나?...‘동방’, ‘성안’ 등 전망은? http://www.pinpointnews.co.kr/view.php?ud=2021021408065794722365609d9b_45
‘이재명 테마주’ 거래 정지 한 달 전, 30억 뺀 사장님 https://www.chosun.com/economy/stock-finance/2021/03/24/NENO4X5M5NDEJPC64HEZE44NAU/?utm_source=naver&utm_medium=referral&utm_campaign=naver-news
재보선 D-1…정치 테마주 추이는 http://www.newsis.com/view/?id=NISX20210406_0001397244&cID=15001&pID=15000
車부품주 웃고 이월드 울다 http://www.imaeil.com/sub_news/sub_news_view.php?news_id=76289&yy=2011
요동치는 정치인 테마주, 개인은 '손실' 오너는 '수익' http://www.fnnews.com/news/202103241536374639


<<<비케이탑스>>>뉴스를 읽고 투자를 결정하세요
[베스트&워스트] 대북ㆍ리비안 관련주 급등 https://www.etoday.co.kr/news/view/2066220
[베스트&워스트] ‘윤석열 테마주’ 엇갈린 희비…원전 관련주는 ‘급등’ https://www.etoday.co.kr/news/view/2034998
[더벨][바이오 복수전공 명암]공수표 전락한 신사업, 주가 상승분 80% 반납 http://www.thebell.co.kr/front/free/contents/news/article_view.asp?key=202102181105402640104051
[심층추적]설계자·브로커·기업사냥꾼…라임 사태의 또 다른 몸통들 https://www.thepublic.kr/news/newsview.php?ncode=1065623604832384
[베스트&워스트] 코로나19 관련주, 줄줄이 급락… 영진제약 22.25%↓ https://www.etoday.co.kr/news/view/1924793

# **그 중에서 사용자가 하나의 동전주를 선택하였을때, 차트를 분석하여 투자하는 습관을 기르도록 하기**

- 만약 선택한 동전주가 "인디에프"라면 매매 결정요소 데이터를 보여준다
- 묻지마 투자가 아닌 데이터를 분석하여 투자할 수 있는 습관을 기르도록한다

In [137]:
select = "인디에프"
print("거래를 하기전, 항상 정보를 분석해보는 습관을 기릅시다!")

select_info = df[df['종목명']==select]

print(f"========{select}종목의 정보===========")
print(f"거래량 : {select_info['거래량'].values[0]}")
print(f"등락률 : {select_info['등락률'].values[0]}")
print(f"액면가 : {select_info['액면가'].values[0]}")
print(f"시가총액 : {select_info['시가총액'].values[0]}")
print(f"상장주식수 : {select_info['상장주식수'].values[0]}")
print(f"거래량 : {select_info['거래량'].values[0]}")
print(f"PER : {select_info['PER'].values[0]}")
print(f"ROE : {select_info['ROE'].values[0]}")

거래를 하기전, 항상 정보를 분석해보는 습관을 기릅시다!
========인디에프종목의 정보===========
거래량 : 11778.0
등락폭 : +0.52%
액면가 : 500.0
시가총액 : 552.0
상장주식수 : 70713.0
거래량 : 11778.0
PER : -2.47
ROE : -50.83

In [237]:
words = pd.DataFrame()
words['word'] = ['액면가','시가총액','PER','ROE']

# 더욱 다양한 재무 데이터를 활용할 수 있지만 예시로 4개를 사용하도록하자
link = [0]*4

for i in range(0,4):
  link[i]= "https://namu.wiki/w/{0}".format(words['word'][i])
  print(link[i])
words['link'] = link

https://namu.wiki/w/액면가
https://namu.wiki/w/시가총액
https://namu.wiki/w/PER
https://namu.wiki/w/ROE

In [240]:
# 데이터의 의미와 해석하는 방법을 "주식거래" 측면에서 알 수 있도록 입력한다

#액면가
tip = [0]*4
meaning = [0]*4

meaning[0] = "주식이나 채권의 표면에 표시되어 있는 가격. 실제 거래가와는 관계없이 표면가격을 의미한다."
tip[0] = "일반적으로 주가가 액면가보다는 높아야 정상적인 기업이라고 평가된다. 코스피 상장기업은 주가가 액면가의 20% 미만인 경우가 30일간 지속되면 관리종목에 지정되며 관리종목 지정 후 90일 내에 액면가의 20% 이상의 주가를 회복하지 못하면 상장폐지된다."

# 시가총액
meaning[1] = "시가총액은 말 그대로 현재 상태의 주식시장의 규모가 얼마나 되는지 판단할 수 있는 지표다"
tip[1] = "시가총액식[(개별 상장종목의 주식수)×(개별 상장종목의 현재가)] 주가지수의 경우, 주가지수에 미치는 영향은 시가총액이 크면 클수록 더 커진다."

# PER
meaning[2] = "주가를 주당순이익으로 나눈 것으로, 주가가 주당 순이익의 배율이 얼마인가를 나타내는 지표이다"
tip[2] = "PER가 낮을 경우 해당 회사가 거둔 이익에 비해 주가가 낮고 그에 따라 기업의 가치에 비해 주가가 저평가되어 있다는 의미로 볼 수 있다. 반대로 PER가 높으면 거둔 이익에 비해 주가가 고평가되었음을 의미한다."

# ROE
meaning[3] = "기업이 자기자본(주주지분)을 활용해 1년간 얼마를 벌어들였는가를 나타내는 대표적인 수익성 지표로 경영효율성을 표시해 준다"
tip[3] = "ROE가 높다는 것은 자기자본에 비해 그만큼 당기순이익을 많이 내 효율적인 영업활동을 했다는 뜻이다. 그렇기 때문에 이 수치가 높은 종목일수록 주식투자자의 투자수익률을 높여준다고 볼 수 있어 투자자 측면에선 이익의 척도가 된다."

In [242]:
# 재무 단어를 모르는 초보자들을 위해
# 1. 용어가 잘 기술된 link, 2. 수치를 해석하는 tip, 3. 단어의 의미를 아래와 같이 보여준다

words['tip'] = tip
words['meaning'] = meaning
words

,word,link,tip,meaning
0,액면가,https://namu.wiki/w/액면가,일반적으로 주가가 액면가보다는 높아야 정상적인 기업이라고 평가된다. 코스피 상장기업...,주식이나 채권의 표면에 표시되어 있는 가격. 실제 거래가와는 관계없이 표면가격을 의...
1,시가총액,https://namu.wiki/w/시가총액,"시가총액식[(개별 상장종목의 주식수)×(개별 상장종목의 현재가)] 주가지수의 경우,...",시가총액은 말 그대로 현재 상태의 주식시장의 규모가 얼마나 되는지 판단할 수 있는 지표다
2,PER,https://namu.wiki/w/PER,PER가 낮을 경우 해당 회사가 거둔 이익에 비해 주가가 낮고 그에 따라 기업의 가...,"주가를 주당순이익으로 나눈 것으로, 주가가 주당 순이익의 배율이 얼마인가를 나타내는..."
3,ROE,https://namu.wiki/w/ROE,ROE가 높다는 것은 자기자본에 비해 그만큼 당기순이익을 많이 내 효율적인 영업활동...,기업이 자기자본(주주지분)을 활용해 1년간 얼마를 벌어들였는가를 나타내는 대표적인 ...

# **사용자는 1000원 미만 주식인 동전주를 활용해 부담없는 실전투자를 진행**

In [246]:
num = input(" 몇 주 거래 : ")
money = input(" 몇 원 매수 : ")

print("총 (  {0}  )원 거래를 진행합니다".format(int(num)*int(money)))

 몇 주 거래 : 1
 몇 원 매수 : 761
총 (  761  )원 거래를 진행합니다

# **사용자는 구매한 종목에 대한 뉴스 기사를 보며 매도 타이밍을 공부한다**

- 사용자가 구매한 종목에 대한 뉴스기사를 크롤링을 해서 가져온다
- 매도 여부를 결정하기 위해 장 시작시간 10분전인 8시50분에 관련 뉴스를 보여주어 종목의 흐름을 파악한다

In [258]:
User_coin = ['인디에프', 'SK증권'] # 사용자가 매수한 동전주에 인디에프, sk증권이 있다고하자

In [269]:
for stock in User_coin:
  print(stock)
  resp = requests.get(f"https://search.naver.com/search.naver?where=news&sm=tab_jum&query=동전주{stock}") # 사용자가 가진 동전주의 뉴스를 가져옴
  print('<<<{0}>>>뉴스를 읽고 매도를 결정하세요'.format(stock))
  html = resp.text
  soup = BeautifulSoup(html,"html.parser")
  links = soup.select('.news_tit')
  for link in links: #각 link는 <a>내용 </a> 의 html
      title = link.text # 태그 안에 텍스트요소 가져온다! -> 제목
      url = link.attrs['href'] # href=""의 속성값을 가져온다. -> 링크
      print(title, url) # 제목, 링크 크롤링 완료!
  print("\n")

인디에프
<<<인디에프>>>뉴스를 읽고 매도를 결정하세요
[여의도퍼트롤]종목도 싼 게 비지떡?…황제주 오를때 동전주 더 빠져 http://www.hankyung.com/news/app/newsview.php?aid=2013042394006
동전주 줄어든 대신 고가주 늘어 http://www.ajunews.com/kor/view.jsp?newsId=20130710000304
올해 코스닥 1천 원 이하 '동전주' 줄었다 http://news20.busan.com/controller/newsController.jsp?newsId=20130712000034
올해 들어 코스닥 동전주 14% 감소 https://n.news.naver.com/mnews/article/001/0006363495?sid=101
인디에프, 북한리스크에 16일만에 무너진 지폐주의 꿈 http://www.etoday.co.kr/news/section/newsview.php?idxno=715929
[베스트&워스트]코스피, 4년간 적자를 흑자로 공시한 ‘한신공영’ 33% 뚝 http://www.etoday.co.kr/news/section/newsview.php?idxno=981392
SK증권·일신바이오·대성창투, 더이상 동전株 아닙니다 http://www.hankyung.com/news/app/newsview.php?aid=2014080772941
고가주 ‘늘고’ 저가주 ‘줄고’ http://www.fnnews.com/view?ra=Sent0301m_01A&corp=fnnews&arcid=201307110334329683432968&cDateYear=2013&cDateMonth=07&cDateDay=11&
올들어 가장 많이 오른 종목은 230% 오른 바로… http://news.mk.co.kr/news_forward.php?domain=news&no=564902&year=2013
올해 고가주 비중 늘었다 http://www.dt.co.kr/contents.html?article_no=2013071002019957780003


SK증권
<<<SK증권>>>뉴스를 읽고 매도를 결정하세요
보통주는 700원인데 우선주는 3000원이 넘네…SK증권의 굴욕 https://biz.chosun.com/stock/stock_general/2022/07/22/TN7XU7MUPJH4POKNGEYNA5SAQE/?utm_source=naver&utm_medium=original&utm_campaign=biz
`동전주` 벗어난 SK증권…우리사주 털어내는 직원들 http://www.edaily.co.kr/news/newspath.asp?newsid=01216886625802704
SK바이오팜 효과? 동전주 벗어난 SK증권 http://news.mt.co.kr/mtview.php?no=2020061609552723306
긴축 시작되자 韓 증시서 사라진 황제주…동전주만 약 두 배 증가 https://www.hankyung.com/finance/article/202205167708i
바닥 뚫린 증권주…52주 신저가 경신 ‘11곳’ https://www.ceoscoredaily.com/page/view/2022061315464969997
[종목돋보기] 동전주된 SK증권 http://biz.chosun.com/site/data/html_dir/2013/08/23/2013082300543.html
조정장에 1000원 미만 ‘동전주’ 속출 http://www.fnnews.com/view?ra=Sent0301m_01A&corp=fnnews&arcid=0922424669&cDateYear=2011&cDateMonth=09&cDateDay=26&
'주가 반토막' 증권사들 자사주 매입 러시…상승 약발 먹혔나 살펴보니 http://www.asiatoday.co.kr/view.php?key=20200325010016144
"급등하는 우선주, 변동성 확대 유의하라" //www.yeongnam.com/web/view.php?key=20200621010002961
한달새 '5만원→75만원'…우선주에 꽂힌 동학개미들 http://www.inews24.com/view/1274954